// lib/core/constants/mock_providers_data.dart

import 'package:booking_app/features/home/data/models/service_model.dart';
import 'package:booking_app/features/home/data/models/service_provider_model.dart';

// Mock Service Providers
final List<ServiceProviderModel> mockProviders = [
  ServiceProviderModel(
    id: 'provider_1',
    name: 'Cool Tech Services',
    description: 'Professional aircon services with 10+ years experience',
    category: 'Aircon Services',
    imageUrl: 'https://via.placeholder.com/150',
    rating: 4.8,
    reviewCount: 234,
    address: 'Toril, Davao City',
    phone: '+63 912 345 6789',
    isAvailable: true,
    serviceTypes: ['Cleaning', 'Maintenance', 'Installation'],
  ),
  ServiceProviderModel(
    id: 'provider_2',
    name: 'Fix Flow Plumbing',
    description: 'Expert plumbing solutions for residential and commercial',
    category: 'Plumbing Services',
    imageUrl: 'https://via.placeholder.com/150',
    rating: 4.6,
    reviewCount: 189,
    address: 'Bajada, Davao City',
    phone: '+63 923 456 7890',
    isAvailable: true,
    serviceTypes: ['Leak Repair', 'Installation', 'Drainage'],
  ),
  ServiceProviderModel(
    id: 'provider_3',
    name: 'Bright Electric',
    description: 'Licensed electricians for safe and reliable electrical work',
    category: 'Electrical Services',
    imageUrl: 'https://via.placeholder.com/150',
    rating: 4.7,
    reviewCount: 156,
    address: 'Matina, Davao City',
    phone: '+63 934 567 8901',
    isAvailable: true,
    serviceTypes: ['Wiring', 'Repair', 'Lighting'],
  ),
];

// Mock Services
final List<ServiceModel> mockServices = [
  // Cool Tech Services (Aircon)
  ServiceModel(
    id: 'service_1',
    providerId: 'provider_1',
    providerName: 'Cool Tech Services',
    name: 'Aircon Cleaning',
    description: 'Deep cleaning of aircon unit including filters and coils',
    price: 500.0,
    duration: '1-2 hours',
    category: 'Aircon Services',
    isAvailable: true,
  ),
  ServiceModel(
    id: 'service_2',
    providerId: 'provider_1',
    providerName: 'Cool Tech Services',
    name: 'Aircon Maintenance',
    description: 'Complete maintenance check and tune-up',
    price: 800.0,
    duration: '2-3 hours',
    category: 'Aircon Services',
    isAvailable: true,
  ),
  ServiceModel(
    id: 'service_3',
    providerId: 'provider_1',
    providerName: 'Cool Tech Services',
    name: 'Aircon Installation',
    description: 'Professional installation of new aircon unit',
    price: 1200.0,
    duration: '3-4 hours',
    category: 'Aircon Services',
    isAvailable: true,
  ),
  
  // Fix Flow Plumbing
  ServiceModel(
    id: 'service_4',
    providerId: 'provider_2',
    providerName: 'Fix Flow Plumbing',
    name: 'Leak Repair',
    description: 'Fix leaking pipes, faucets, and fixtures',
    price: 400.0,
    duration: '1-2 hours',
    category: 'Plumbing Services',
    isAvailable: true,
  ),
  ServiceModel(
    id: 'service_5',
    providerId: 'provider_2',
    providerName: 'Fix Flow Plumbing',
    name: 'Pipe Installation',
    description: 'Installation of new pipes and plumbing systems',
    price: 800.0,
    duration: '2-4 hours',
    category: 'Plumbing Services',
    isAvailable: true,
  ),
  ServiceModel(
    id: 'service_6',
    providerId: 'provider_2',
    providerName: 'Fix Flow Plumbing',
    name: 'Drainage Cleaning',
    description: 'Clear blocked drains and sewers',
    price: 600.0,
    duration: '1-3 hours',
    category: 'Plumbing Services',
    isAvailable: true,
  ),
  
  // Bright Electric
  ServiceModel(
    id: 'service_7',
    providerId: 'provider_3',
    providerName: 'Bright Electric',
    name: 'Wiring Installation',
    description: 'New electrical wiring for homes and offices',
    price: 1000.0,
    duration: '3-5 hours',
    category: 'Electrical Services',
    isAvailable: true,
  ),
  ServiceModel(
    id: 'service_8',
    providerId: 'provider_3',
    providerName: 'Bright Electric',
    name: 'Outlet Repair',
    description: 'Fix damaged outlets and switches',
    price: 300.0,
    duration: '30min - 1 hour',
    category: 'Electrical Services',
    isAvailable: true,
  ),
  ServiceModel(
    id: 'service_9',
    providerId: 'provider_3',
    providerName: 'Bright Electric',
    name: 'Lighting Setup',
    description: 'Installation of indoor and outdoor lighting',
    price: 700.0,
    duration: '2-3 hours',
    category: 'Electrical Services',
    isAvailable: true,
  ),
];