// lib/core/constants/mock_providers_data.dart

import 'package:booking_app/features/home/data/models/service_model.dart';
import 'package:booking_app/features/home/data/models/service_provider_model.dart';

// Mock Service Providers (Merchants/Stores)
final List<ServiceProviderModel> mockProviders = [
  // Hablon Fabric Store
  ServiceProviderModel(
    id: 'provider_1',
    name: 'Iloilo Hablon Weaving Center',
    description: 'Authentic hand-woven hablon fabrics and traditional textiles',
    category: 'Textile & Fabric Items',
    imageUrl: 'https://via.placeholder.com/150',
    rating: 4.9,
    reviewCount: 312,
    address: 'Miagao, Iloilo',
    phone: '+63 912 345 6789',
    isAvailable: true,
    serviceTypes: ['Hablon Fabric', 'Patadyong', 'Shawls'],
  ),

  // Traditional Clothing Store
  ServiceProviderModel(
    id: 'provider_2',
    name: 'Barong & Patadyong Hub',
    description: 'Traditional Filipino clothing made from premium hablon',
    category: 'Traditional Clothing',
    imageUrl: 'https://via.placeholder.com/150',
    rating: 4.8,
    reviewCount: 245,
    address: 'La Paz, Iloilo City',
    phone: '+63 923 456 7890',
    isAvailable: true,
    serviceTypes: ['Barong', 'Patadyong', 'Custom Tailoring'],
  ),

  // Accessories Store
  ServiceProviderModel(
    id: 'provider_3',
    name: 'Hablon Craft & Accessories',
    description: 'Handcrafted bags and accessories made with hablon fabric',
    category: 'Wearable Accessories',
    imageUrl: 'https://via.placeholder.com/150',
    rating: 4.7,
    reviewCount: 189,
    address: 'Jaro, Iloilo City',
    phone: '+63 934 567 8901',
    isAvailable: true,
    serviceTypes: ['Handbags', 'Tote Bags', 'Pouches'],
  ),

  // Home Decor Store
  ServiceProviderModel(
    id: 'provider_4',
    name: 'Hablon Home & Decor',
    description: 'Beautiful hablon items for home decoration and lifestyle',
    category: 'Home & Lifestyle',
    imageUrl: 'https://via.placeholder.com/150',
    rating: 4.6,
    reviewCount: 156,
    address: 'Molo, Iloilo City',
    phone: '+63 935 678 9012',
    isAvailable: true,
    serviceTypes: ['Table Runners', 'Placemats', 'Throw Pillows'],
  ),

  // Tech Accessories Store
  ServiceProviderModel(
    id: 'provider_5',
    name: 'Modern Hablon Tech',
    description: 'Contemporary hablon accessories for modern lifestyle',
    category: 'Tech Accessories',
    imageUrl: 'https://via.placeholder.com/150',
    rating: 4.8,
    reviewCount: 201,
    address: 'City Proper, Iloilo City',
    phone: '+63 936 789 0123',
    isAvailable: true,
    serviceTypes: ['Laptop Sleeves', 'Tablet Cases', 'Cord Rolls'],
  ),

  // Shawls & Wraps Boutique
  ServiceProviderModel(
    id: 'provider_6',
    name: 'Elegant Hablon Wraps',
    description: 'Premium shawls and wraps for all occasions',
    category: 'Shawls & Wraps',
    imageUrl: 'https://via.placeholder.com/150',
    rating: 4.9,
    reviewCount: 267,
    address: 'Mandurriao, Iloilo City',
    phone: '+63 937 890 1234',
    isAvailable: true,
    serviceTypes: ['Formal Shawls', 'Casual Wraps', 'Wedding Shawls'],
  ),

  // Sling Bags Store
  ServiceProviderModel(
    id: 'provider_7',
    name: 'Hablon Bag Collection',
    description: 'Stylish hablon bags for everyday use',
    category: 'Bags & Carriers',
    imageUrl: 'https://via.placeholder.com/150',
    rating: 4.7,
    reviewCount: 178,
    address: 'Arevalo, Iloilo City',
    phone: '+63 938 901 2345',
    isAvailable: true,
    serviceTypes: ['Sling Bags', 'Crossbody Bags', 'Wristlets'],
  ),
];

// Mock Services (Products)
final List<ServiceModel> mockServices = [
  // Iloilo Hablon Weaving Center - Textile & Fabric Items
  ServiceModel(
    id: 'service_1',
    providerId: 'provider_1',
    providerName: 'Iloilo Hablon Weaving Center',
    name: 'Hablon Fabric - Plaid Pattern',
    description: 'Hand-woven hablon fabric with traditional plaid design (per meter)',
    price: 350.0,
    duration: 'In Stock',
    category: 'Textile & Fabric Items',
    isAvailable: true,
  ),
  ServiceModel(
    id: 'service_2',
    providerId: 'provider_1',
    providerName: 'Iloilo Hablon Weaving Center',
    name: 'Hablon Fabric - Striped',
    description: 'Beautiful striped hablon cloth for tailoring (per meter)',
    price: 320.0,
    duration: 'In Stock',
    category: 'Textile & Fabric Items',
    isAvailable: true,
  ),
  ServiceModel(
    id: 'service_3',
    providerId: 'provider_1',
    providerName: 'Iloilo Hablon Weaving Center',
    name: 'Patadyong - Traditional Wrap Skirt',
    description: 'Authentic patadyong wrap-around skirt in various colors',
    price: 850.0,
    duration: 'In Stock',
    category: 'Textile & Fabric Items',
    isAvailable: true,
  ),

  // Barong & Patadyong Hub - Traditional Clothing
  ServiceModel(
    id: 'service_4',
    providerId: 'provider_2',
    providerName: 'Barong & Patadyong Hub',
    name: 'Hablon Barong Tagalog',
    description: 'Elegant barong made from premium hablon fabric',
    price: 2500.0,
    duration: 'Made to Order',
    category: 'Traditional Clothing',
    isAvailable: true,
  ),
  ServiceModel(
    id: 'service_5',
    providerId: 'provider_2',
    providerName: 'Barong & Patadyong Hub',
    name: 'Custom Patadyong',
    description: 'Custom-tailored patadyong with your choice of hablon pattern',
    price: 1200.0,
    duration: '3-5 days',
    category: 'Traditional Clothing',
    isAvailable: true,
  ),
  ServiceModel(
    id: 'service_6',
    providerId: 'provider_2',
    providerName: 'Barong & Patadyong Hub',
    name: 'Traditional Hablon Dress',
    description: 'Beautiful dress sewn from authentic hablon fabric',
    price: 1800.0,
    duration: 'Made to Order',
    category: 'Traditional Clothing',
    isAvailable: true,
  ),

  // Hablon Craft & Accessories - Wearable Accessories
  ServiceModel(
    id: 'service_7',
    providerId: 'provider_3',
    providerName: 'Hablon Craft & Accessories',
    name: 'Hablon Handbag',
    description: 'Stylish handbag crafted with premium hablon fabric',
    price: 650.0,
    duration: 'In Stock',
    category: 'Wearable Accessories',
    isAvailable: true,
  ),
  ServiceModel(
    id: 'service_8',
    providerId: 'provider_3',
    providerName: 'Hablon Craft & Accessories',
    name: 'Hablon Tote Bag',
    description: 'Spacious tote bag perfect for everyday use',
    price: 550.0,
    duration: 'In Stock',
    category: 'Wearable Accessories',
    isAvailable: true,
  ),
  ServiceModel(
    id: 'service_9',
    providerId: 'provider_3',
    providerName: 'Hablon Craft & Accessories',
    name: 'Small Pouch Set',
    description: 'Set of 3 small carry pouches with hablon design',
    price: 280.0,
    duration: 'In Stock',
    category: 'Wearable Accessories',
    isAvailable: true,
  ),

  // Hablon Home & Decor
  ServiceModel(
    id: 'service_10',
    providerId: 'provider_4',
    providerName: 'Hablon Home & Decor',
    name: 'Hablon Table Runner',
    description: 'Elegant table runner with traditional hablon weave',
    price: 450.0,
    duration: 'In Stock',
    category: 'Home & Lifestyle',
    isAvailable: true,
  ),
  ServiceModel(
    id: 'service_11',
    providerId: 'provider_4',
    providerName: 'Hablon Home & Decor',
    name: 'Hablon Placemats (Set of 4)',
    description: 'Beautiful placemats to enhance your dining experience',
    price: 380.0,
    duration: 'In Stock',
    category: 'Home & Lifestyle',
    isAvailable: true,
  ),
  ServiceModel(
    id: 'service_12',
    providerId: 'provider_4',
    providerName: 'Hablon Home & Decor',
    name: 'Hablon Throw Pillow',
    description: 'Decorative throw pillow with hablon fabric cover',
    price: 320.0,
    duration: 'In Stock',
    category: 'Home & Lifestyle',
    isAvailable: true,
  ),

  // Modern Hablon Tech - Tech Accessories
  ServiceModel(
    id: 'service_13',
    providerId: 'provider_5',
    providerName: 'Modern Hablon Tech',
    name: 'Laptop Sleeve - 13 inch',
    description: 'Protective laptop sleeve with hablon exterior design',
    price: 580.0,
    duration: 'In Stock',
    category: 'Tech Accessories',
    isAvailable: true,
  ),
  ServiceModel(
    id: 'service_14',
    providerId: 'provider_5',
    providerName: 'Modern Hablon Tech',
    name: 'Tablet Case - Universal',
    description: 'Padded tablet case featuring hablon weave pattern',
    price: 480.0,
    duration: 'In Stock',
    category: 'Tech Accessories',
    isAvailable: true,
  ),
  ServiceModel(
    id: 'service_15',
    providerId: 'provider_5',
    providerName: 'Modern Hablon Tech',
    name: 'Cord Roll Organizer',
    description: 'Keep your cables organized with hablon cord roll',
    price: 180.0,
    duration: 'In Stock',
    category: 'Tech Accessories',
    isAvailable: true,
  ),

  // Elegant Hablon Wraps - Shawls & Wraps
  ServiceModel(
    id: 'service_16',
    providerId: 'provider_6',
    providerName: 'Elegant Hablon Wraps',
    name: 'Formal Hablon Shawl',
    description: 'Elegant shawl perfect for formal occasions and events',
    price: 1200.0,
    duration: 'In Stock',
    category: 'Shawls & Wraps',
    isAvailable: true,
  ),
  ServiceModel(
    id: 'service_17',
    providerId: 'provider_6',
    providerName: 'Elegant Hablon Wraps',
    name: 'Casual Hablon Wrap',
    description: 'Versatile wrap for everyday casual wear',
    price: 750.0,
    duration: 'In Stock',
    category: 'Shawls & Wraps',
    isAvailable: true,
  ),
  ServiceModel(
    id: 'service_18',
    providerId: 'provider_6',
    providerName: 'Elegant Hablon Wraps',
    name: 'Wedding Shawl - Premium',
    description: 'Exquisite handwoven shawl for weddings and special occasions',
    price: 2800.0,
    duration: 'Made to Order',
    category: 'Shawls & Wraps',
    isAvailable: true,
  ),

  // Hablon Bag Collection - Bags & Carriers
  ServiceModel(
    id: 'service_19',
    providerId: 'provider_7',
    providerName: 'Hablon Bag Collection',
    name: 'Hablon Sling Bag',
    description: 'Compact sling bag with adjustable strap and hablon design',
    price: 480.0,
    duration: 'In Stock',
    category: 'Bags & Carriers',
    isAvailable: true,
  ),
  ServiceModel(
    id: 'service_20',
    providerId: 'provider_7',
    providerName: 'Hablon Bag Collection',
    name: 'Crossbody Bag',
    description: 'Stylish crossbody bag perfect for hands-free convenience',
    price: 620.0,
    duration: 'In Stock',
    category: 'Bags & Carriers',
    isAvailable: true,
  ),
  ServiceModel(
    id: 'service_21',
    providerId: 'provider_7',
    providerName: 'Hablon Bag Collection',
    name: 'Wristlet Purse',
    description: 'Small wristlet for carrying essentials with hablon accent',
    price: 280.0,
    duration: 'In Stock',
    category: 'Bags & Carriers',
    isAvailable: true,
  ),
];

// ============================================================================
// OLD MOCK DATA (COMMENTED OUT FOR REFERENCE)
// ============================================================================

// // OLD SERVICE PROVIDER DATA
// final List<ServiceProviderModel> mockProviders = [
//   // Aircon
//   ServiceProviderModel(
//     id: 'provider_1',
//     name: 'Cool Tech Services',
//     description: 'Professional aircon services with 10+ years experience',
//     category: 'Aircon Services',
//     imageUrl: 'https://via.placeholder.com/150',
//     rating: 4.8,
//     reviewCount: 234,
//     address: 'Toril, Davao City',
//     phone: '+63 912 345 6789',
//     isAvailable: true,
//     serviceTypes: ['Cleaning', 'Maintenance', 'Installation'],
//   ),
//
//   // Plumbing
//   ServiceProviderModel(
//     id: 'provider_2',
//     name: 'Fix Flow Plumbing',
//     description: 'Expert plumbing solutions for residential and commercial',
//     category: 'Plumbing Services',
//     imageUrl: 'https://via.placeholder.com/150',
//     rating: 4.6,
//     reviewCount: 189,
//     address: 'Bajada, Davao City',
//     phone: '+63 923 456 7890',
//     isAvailable: true,
//     serviceTypes: ['Leak Repair', 'Installation', 'Drainage'],
//   ),
//
//   // Electrical
//   ServiceProviderModel(
//     id: 'provider_3',
//     name: 'Bright Electric',
//     description: 'Licensed electricians for safe and reliable electrical work',
//     category: 'Electrical Services',
//     imageUrl: 'https://via.placeholder.com/150',
//     rating: 4.7,
//     reviewCount: 156,
//     address: 'Matina, Davao City',
//     phone: '+63 934 567 8901',
//     isAvailable: true,
//     serviceTypes: ['Wiring', 'Repair', 'Lighting'],
//   ),
//
//   // Car
//   ServiceProviderModel(
//     id: 'provider_4',
//     name: 'AutoCare Garage',
//     description: 'Complete car maintenance and repair services',
//     category: 'Car Services',
//     imageUrl: 'https://via.placeholder.com/150',
//     rating: 4.5,
//     reviewCount: 210,
//     address: 'Lanang, Davao City',
//     phone: '+63 935 678 9012',
//     isAvailable: true,
//     serviceTypes: ['Oil Change', 'Tire Replacement', 'Engine Tune-Up'],
//   ),
//
//   // Appliance
//   ServiceProviderModel(
//     id: 'provider_5',
//     name: 'Appliance Fix Pro',
//     description: 'Reliable appliance repair for all major brands',
//     category: 'Appliance Services',
//     imageUrl: 'https://via.placeholder.com/150',
//     rating: 4.6,
//     reviewCount: 175,
//     address: 'Buhangin, Davao City',
//     phone: '+63 936 789 0123',
//     isAvailable: true,
//     serviceTypes: ['Refrigerator Repair', 'Washing Machine Repair', 'Aircon Repair'],
//   ),
//
//   // Construction
//   ServiceProviderModel(
//     id: 'provider_6',
//     name: 'BuildRight Construction',
//     description: 'Quality construction and renovation services',
//     category: 'Construction Services',
//     imageUrl: 'https://via.placeholder.com/150',
//     rating: 4.9,
//     reviewCount: 320,
//     address: 'Ecoland, Davao City',
//     phone: '+63 937 890 1234',
//     isAvailable: true,
//     serviceTypes: ['House Renovation', 'Roofing', 'Painting'],
//   ),
//
//   // IT
//   ServiceProviderModel(
//     id: 'provider_7',
//     name: 'TechFix IT Solutions',
//     description: 'Professional IT support and computer repair',
//     category: 'IT Services',
//     imageUrl: 'https://via.placeholder.com/150',
//     rating: 4.8,
//     reviewCount: 198,
//     address: 'Downtown, Davao City',
//     phone: '+63 938 901 2345',
//     isAvailable: true,
//     serviceTypes: ['Computer Repair', 'Network Setup', 'Data Recovery'],
//   ),
// ];

// // OLD SERVICES DATA
// final List<ServiceModel> mockServices = [
//   // Cool Tech Services (Aircon)
//   ServiceModel(
//     id: 'service_1',
//     providerId: 'provider_1',
//     providerName: 'Cool Tech Services',
//     name: 'Aircon Cleaning',
//     description: 'Deep cleaning of aircon unit including filters and coils',
//     price: 500.0,
//     duration: '1-2 hours',
//     category: 'Aircon Services',
//     isAvailable: true,
//   ),
//   ServiceModel(
//     id: 'service_2',
//     providerId: 'provider_1',
//     providerName: 'Cool Tech Services',
//     name: 'Aircon Maintenance',
//     description: 'Complete maintenance check and tune-up',
//     price: 800.0,
//     duration: '2-3 hours',
//     category: 'Aircon Services',
//     isAvailable: true,
//   ),
//   ServiceModel(
//     id: 'service_3',
//     providerId: 'provider_1',
//     providerName: 'Cool Tech Services',
//     name: 'Aircon Installation',
//     description: 'Professional installation of new aircon unit',
//     price: 1200.0,
//     duration: '3-4 hours',
//     category: 'Aircon Services',
//     isAvailable: true,
//   ),
//
//   // Fix Flow Plumbing
//   ServiceModel(
//     id: 'service_4',
//     providerId: 'provider_2',
//     providerName: 'Fix Flow Plumbing',
//     name: 'Leak Repair',
//     description: 'Fix leaking pipes, faucets, and fixtures',
//     price: 400.0,
//     duration: '1-2 hours',
//     category: 'Plumbing Services',
//     isAvailable: true,
//   ),
//   ServiceModel(
//     id: 'service_5',
//     providerId: 'provider_2',
//     providerName: 'Fix Flow Plumbing',
//     name: 'Pipe Installation',
//     description: 'Installation of new pipes and plumbing systems',
//     price: 800.0,
//     duration: '2-4 hours',
//     category: 'Plumbing Services',
//     isAvailable: true,
//   ),
//   ServiceModel(
//     id: 'service_6',
//     providerId: 'provider_2',
//     providerName: 'Fix Flow Plumbing',
//     name: 'Drainage Cleaning',
//     description: 'Clear blocked drains and sewers',
//     price: 600.0,
//     duration: '1-3 hours',
//     category: 'Plumbing Services',
//     isAvailable: true,
//   ),
//
//   // Bright Electric
//   ServiceModel(
//     id: 'service_7',
//     providerId: 'provider_3',
//     providerName: 'Bright Electric',
//     name: 'Wiring Installation',
//     description: 'New electrical wiring for homes and offices',
//     price: 1000.0,
//     duration: '3-5 hours',
//     category: 'Electrical Services',
//     isAvailable: true,
//   ),
//   ServiceModel(
//     id: 'service_8',
//     providerId: 'provider_3',
//     providerName: 'Bright Electric',
//     name: 'Outlet Repair',
//     description: 'Fix damaged outlets and switches',
//     price: 300.0,
//     duration: '30min - 1 hour',
//     category: 'Electrical Services',
//     isAvailable: true,
//   ),
//   ServiceModel(
//     id: 'service_9',
//     providerId: 'provider_3',
//     providerName: 'Bright Electric',
//     name: 'Lighting Setup',
//     description: 'Installation of indoor and outdoor lighting',
//     price: 700.0,
//     duration: '2-3 hours',
//     category: 'Electrical Services',
//     isAvailable: true,
//   ),
//
//   // AutoCare Garage (Car)
//   ServiceModel(
//     id: 'service_10',
//     providerId: 'provider_4',
//     providerName: 'AutoCare Garage',
//     name: 'Oil Change',
//     description: 'Replace old engine oil and filter for better performance',
//     price: 600.0,
//     duration: '1 hour',
//     category: 'Car Services',
//     isAvailable: true,
//   ),
//   ServiceModel(
//     id: 'service_11',
//     providerId: 'provider_4',
//     providerName: 'AutoCare Garage',
//     name: 'Tire Replacement',
//     description: 'Replace old or damaged tires with new ones',
//     price: 1000.0,
//     duration: '1-2 hours',
//     category: 'Car Services',
//     isAvailable: true,
//   ),
//   ServiceModel(
//     id: 'service_12',
//     providerId: 'provider_4',
//     providerName: 'AutoCare Garage',
//     name: 'Engine Tune-Up',
//     description: 'Comprehensive engine check and tuning for optimal performance',
//     price: 1500.0,
//     duration: '2-3 hours',
//     category: 'Car Services',
//     isAvailable: true,
//   ),
//
//   // Appliance Fix Pro
//   ServiceModel(
//     id: 'service_13',
//     providerId: 'provider_5',
//     providerName: 'Appliance Fix Pro',
//     name: 'Refrigerator Repair',
//     description: 'Fix cooling issues, compressor, or temperature control',
//     price: 700.0,
//     duration: '1-2 hours',
//     category: 'Appliance Services',
//     isAvailable: true,
//   ),
//   ServiceModel(
//     id: 'service_14',
//     providerId: 'provider_5',
//     providerName: 'Appliance Fix Pro',
//     name: 'Washing Machine Repair',
//     description: 'Repair spin issues, leaks, or electrical faults',
//     price: 800.0,
//     duration: '2-3 hours',
//     category: 'Appliance Services',
//     isAvailable: true,
//   ),
//   ServiceModel(
//     id: 'service_15',
//     providerId: 'provider_5',
//     providerName: 'Appliance Fix Pro',
//     name: 'Aircon Repair',
//     description: 'Diagnose and fix aircon cooling or electrical problems',
//     price: 900.0,
//     duration: '2-3 hours',
//     category: 'Appliance Services',
//     isAvailable: true,
//   ),
//
//   // BuildRight Construction
//   ServiceModel(
//     id: 'service_16',
//     providerId: 'provider_6',
//     providerName: 'BuildRight Construction',
//     name: 'House Renovation',
//     description: 'Full home renovation including layout and design improvements',
//     price: 50000.0,
//     duration: '3-6 weeks',
//     category: 'Construction Services',
//     isAvailable: true,
//   ),
//   ServiceModel(
//     id: 'service_17',
//     providerId: 'provider_6',
//     providerName: 'BuildRight Construction',
//     name: 'Roofing',
//     description: 'Install or repair roofing materials for leak protection',
//     price: 15000.0,
//     duration: '3-5 days',
//     category: 'Construction Services',
//     isAvailable: true,
//   ),
//   ServiceModel(
//     id: 'service_18',
//     providerId: 'provider_6',
//     providerName: 'BuildRight Construction',
//     name: 'Painting',
//     description: 'Interior and exterior wall painting services',
//     price: 8000.0,
//     duration: '2-4 days',
//     category: 'Construction Services',
//     isAvailable: true,
//   ),
//
//   // TechFix IT Solutions
//   ServiceModel(
//     id: 'service_19',
//     providerId: 'provider_7',
//     providerName: 'TechFix IT Solutions',
//     name: 'Computer Repair',
//     description: 'Hardware and software repair for PCs and laptops',
//     price: 500.0,
//     duration: '1-2 hours',
//     category: 'IT Services',
//     isAvailable: true,
//   ),
//   ServiceModel(
//     id: 'service_20',
//     providerId: 'provider_7',
//     providerName: 'TechFix IT Solutions',
//     name: 'Network Setup',
//     description: 'Install routers, modems, and Wi-Fi connections',
//     price: 700.0,
//     duration: '1-2 hours',
//     category: 'IT Services',
//     isAvailable: true,
//   ),
//   ServiceModel(
//     id: 'service_21',
//     providerId: 'provider_7',
//     providerName: 'TechFix IT Solutions',
//     name: 'Data Recovery',
//     description: 'Recover deleted or lost files from storage devices',
//     price: 1200.0,
//     duration: '2-4 hours',
//     category: 'IT Services',
//     isAvailable: true,
//   ),
// ];